import { CheerioAPI, load as parseHTML } from 'cheerio';
import { fetchApi } from '@libs/fetch';
import { FilterTypes, Filters } from '@libs/filterInputs';
import { Plugin } from '@/types/plugin';
import dayjs from 'dayjs';

class ScribbleHubPlugin implements Plugin.PluginBase {
  id = 'scribblehub';
  name = 'Scribble Hub';
  icon = 'src/en/scribblehub/icon.png';
  site = 'https://www.scribblehub.com/';
  version = 'custom';

  parseNovels(loadedCheerio: CheerioAPI) {
    const novels: Plugin.NovelItem[] = [];

    loadedCheerio('.search_main_box').each((i, el) => {
      const novelName = loadedCheerio(el).find('.search_title > a').text();
      const novelCover = loadedCheerio(el)
        .find('.search_img > img')
        .attr('src');
      const novelUrl = loadedCheerio(el).find('.search_title > a').attr('href');

      if (!novelUrl) return;

      const novel = {
        name: novelName,
        cover: novelCover,
        path: novelUrl.replace(this.site, ''),
      };
      novels.push(novel);
    });
    return novels;
  }

  async popularNovels(
    page: number,
    {
      showLatestNovels,
      filters,
    }: Plugin.PopularNovelsOptions<typeof this.filters>,
  ): Promise<Plugin.NovelItem[]> {
    let url = `${this.site}`;
    if (showLatestNovels) {
      url += `latest-series/?pg=${page}`;
    } else if (filters) {
      const params = new URLSearchParams();
      if (filters.genres.value.include?.length) {
        params.append('gi', filters.genres.value.include.join(','));
      }
      if (
        filters.genres.value.include?.length ||
        filters.genres.value.exclude?.length
      ) {
        params.append('mgi', filters.genre_operator.value);
      }
      if (filters.genres.value.exclude?.length) {
        params.append('ge', filters.genres.value.exclude.join(','));
      }
      if (filters.tags.value.include?.length) {
        params.append('tgi', filters.tags.value.include.join(','));
      }
      if (
        filters.tags.value.include?.length ||
        filters.tags.value.exclude?.length
      ) {
        params.append('mtgi', filters.tag_operator.value);
      }
      if (filters.tags.value.exclude?.length) {
        params.append('tge', filters.tags.value.exclude.join(','));
      }
      if (filters.content_warning.value.include?.length) {
        params.append('cti', filters.content_warning.value.include.join(','));
      }
      if (
        filters.content_warning.value.include?.length ||
        filters.content_warning.value.exclude?.length
      ) {
        params.append('mct', filters.content_warning_operator.value);
      }
      if (filters.content_warning.value.exclude?.length) {
        params.append('cte', filters.content_warning.value.exclude.join(','));
      }
      params.append('cp', filters.storyStatus.value);
      params.append('sort', filters.sort.value);
      params.append('order', filters.order.value);
      params.append('pg', page.toString());
      url += `series-finder/?sf=1&${params.toString()}`;
    } else {
      const date = new Date();
      const lastUpdateMinDate = `${date.getMonth() + 1}/${date.getDate()}/${date.getFullYear()}`;
      url += `series-finder/?sf=1&sort=pageviews&mnlcd=${lastUpdateMinDate}&order=desc&pg=${page}`;
    }

    if (
      url ==
      `${this.site}series-finder/?sf=1&cp=all&sort=pageviews&order=desc&pg=${page}`
    ) {
      const date = new Date();
      const lastUpdateMinDate = `${date.getMonth() + 1}/${date.getDate()}/${date.getFullYear()}`;
      url += `&mnlcd=${lastUpdateMinDate}`;
    }

    const body = await fetchApi(url).then(result => result.text());

    const loadedCheerio = parseHTML(body);
    return this.parseNovels(loadedCheerio);
  }

  async parseNovel(novelPath: string): Promise<Plugin.SourceNovel> {
    const result = await fetchApi(this.site + novelPath);
    const body = await result.text();

    let loadedCheerio = parseHTML(body);

    const novel: Plugin.SourceNovel = {
      path: novelPath,
      name: loadedCheerio('.fic_title').text() || 'Untitled',
      cover: loadedCheerio('.fic_image > img').attr('src'),
      summary: loadedCheerio('.wi_fic_desc').text(),
      author: loadedCheerio('.auth_name_fic').text(),
      chapters: [],
    };

    novel.genres = loadedCheerio('.fic_genre')
      .map((i, el) => loadedCheerio(el).text())
      .toArray()
      .join(',');

    novel.status = loadedCheerio('.rnd_stats').next().text().includes('Ongoing')
      ? 'Ongoing'
      : 'Completed';

    const formData = new FormData();
    formData.append('action', 'wi_getreleases_pagination');
    formData.append('pagenum', '-1');
    formData.append('mypostid', novelPath.split('/')[1]);

    const data = await fetchApi(`${this.site}wp-admin/admin-ajax.php`, {
      method: 'POST',
      body: formData,
    });
    const text = await data.text();

    loadedCheerio = parseHTML(text);

    const chapter: Plugin.ChapterItem[] = [];

    const parseISODate = (date: string) => {
      if (date.includes('ago')) {
        const dayJSDate = dayjs(new Date()); // today
        const timeAgo = date.match(/\d+/)?.[0] || '';
        const timeAgoInt = parseInt(timeAgo, 10);

        if (!timeAgo) return null; // there is no number!

        if (date.includes('hours ago') || date.includes('hour ago')) {
          dayJSDate.subtract(timeAgoInt, 'hours'); // go back N hours
        }

        if (date.includes('days ago') || date.includes('day ago')) {
          dayJSDate.subtract(timeAgoInt, 'days'); // go back N days
        }

        if (date.includes('months ago') || date.includes('month ago')) {
          dayJSDate.subtract(timeAgoInt, 'months'); // go back N months
        }

        return dayJSDate.toISOString();
      }
      return null;
    };

    loadedCheerio('.toc_w').each((i, el) => {
      const chapterName = loadedCheerio(el).find('.toc_a').text();
      const releaseDate = loadedCheerio(el).find('.fic_date_pub').text();
      const chapterUrl = loadedCheerio(el).find('a').attr('href');

      if (!chapterUrl) return;
      chapter.push({
        name: chapterName,
        releaseTime: parseISODate(releaseDate),
        path: chapterUrl.replace(this.site, ''),
      });
    });

    novel.chapters = chapter.reverse();

    return novel;
  }

  async parseChapter(chapterPath: string): Promise<string> {
    const result = await fetchApi(this.site + chapterPath);
    const body = await result.text();

    const loadedCheerio = parseHTML(body);

    const chapterText = loadedCheerio('div.chp_raw').html() || '';
    return chapterText;
  }

  async searchNovels(
    searchTerm: string,
    pageNo: number,
  ): Promise<Plugin.NovelItem[]> {
    const url = `${this.site}series-finder/?sf=1&sh=${encodeURIComponent(searchTerm)}&pg=${pageNo.toString()}`;
    const result = await fetchApi(url);
    const body = await result.text();

    const loadedCheerio = parseHTML(body);
    return this.parseNovels(loadedCheerio);
  }

  filters = {
    sort: {
      label: 'Sort Results By',
      value: 'pageviews',
      options: [
        { label: 'Chapters', value: 'chapters' },
        { label: 'Chapters per Week', value: 'frequency' },
        { label: 'Date Added', value: 'dateadded' },
        { label: 'Favorites', value: 'favorites' },
        { label: 'Last Updated', value: 'lastchdate' },
        { label: 'Number of Ratings', value: 'numofrate' },
        { label: 'Pages', value: 'pages' },
        { label: 'Pageviews', value: 'pageviews' },
        { label: 'Ratings', value: 'ratings' },
        { label: 'Readers', value: 'readers' },
        { label: 'Reviews', value: 'reviews' },
        { label: 'Total Words', value: 'totalwords' },
      ],
      type: FilterTypes.Picker,
    },
    order: {
      label: 'Order By',
      value: 'desc',
      options: [
        { label: 'Descending', value: 'desc' },
        { label: 'Ascending', value: 'asc' },
      ],
      type: FilterTypes.Picker,
    },
    storyStatus: {
      label: 'Story Status',
      value: 'all',
      options: [
        { label: 'All', value: 'all' },
        { label: 'Completed', value: 'completed' },
        { label: 'Ongoing', value: 'ongoing' },
        { label: 'Hiatus', value: 'hiatus' },
      ],
      type: FilterTypes.Picker,
    },
    genre_operator: {
      value: 'and',
      label: 'Genres (And/Or)',
      options: [
        { label: 'And', value: 'and' },
        { label: 'Or', value: 'or' },
      ],
      type: FilterTypes.Picker,
    },
    genres: {
      label: 'Genres',
      value: {
        include: [],
        exclude: [],
      },
      options: [
        { label: 'Action', value: '9' },
        { label: 'Adult', value: '902' },
        { label: 'Adventure', value: '8' },
        { label: 'Boys Love', value: '891' },
        { label: 'Comedy', value: '7' },
        { label: 'Drama', value: '903' },
        { label: 'Ecchi', value: '904' },
        { label: 'Fanfiction', value: '38' },
        { label: 'Fantasy', value: '19' },
        { label: 'Gender Bender', value: '905' },
        { label: 'Girls Love', value: '892' },
        { label: 'Harem', value: '1015' },
        { label: 'Historical', value: '21' },
        { label: 'Horror', value: '22' },
        { label: 'Isekai', value: '37' },
        { label: 'Josei', value: '906' },
        { label: 'LitRPG', value: '1180' },
        { label: 'Martial Arts', value: '907' },
        { label: 'Mature', value: '20' },
        { label: 'Mecha', value: '908' },
        { label: 'Mystery', value: '909' },
        { label: 'Psychological', value: '910' },
        { label: 'Romance', value: '6' },
        { label: 'School Life', value: '911' },
        { label: 'Sci-fi', value: '912' },
        { label: 'Seinen', value: '913' },
        { label: 'Slice of Life', value: '914' },
        { label: 'Smut', value: '915' },
        { label: 'Sports', value: '916' },
        { label: 'Supernatural', value: '5' },
        { label: 'Tragedy', value: '901' },
      ],
      type: FilterTypes.ExcludableCheckboxGroup,
    },
    tag_operator: {
      value: 'and',
      label: 'Tags (And/Or)',
      options: [
        { label: 'And', value: 'and' },
        { label: 'Or', value: 'or' },
      ],
      type: FilterTypes.Picker,
    },
    tags: {
      label: 'Tags',
      value: {
        include: [],
        exclude: [],
      },
      options: [
        { label: 'Abandoned Children', value: '119' },
        { label: 'Ability Steal', value: '120' },
        { label: 'Absent Parents', value: '121' },
        { label: 'Abusive Characters', value: '122' },
        { label: 'Academy', value: '123' },
        { label: 'Accelerated Grouth', value: '124' },
        { label: 'Acting', value: '125' },
        { label: 'Adopted Children', value: '137' },
        { label: 'Adopted Protagonist', value: '138' },
        { label: 'Adultery', value: '139' },
        { label: 'Adventures', value: '140' },
        { label: 'Affair', value: '141' },
        { label: 'Age Progression', value: '' },
        { label: 'Age Regression', value: '' },
        { label: 'Aggressive Characters', value: '' },
        { label: 'Alchemy', value: '' },
        { label: 'Aliens', value: '' },
        { label: 'All-Girls School', value: '' },
        { label: 'Alternate World', value: '' },
        { label: 'Amnesia', value: '' },
        { label: 'Amusement Park', value: '' },
        { label: 'Ancient China', value: '' },
        { label: 'Ancient Times', value: '' },
        { label: 'Androgynous Characters', value: '' },
        { label: 'Androids', value: '' },
        { label: 'Angels', value: '' },
        { label: 'Animal Characteristics', value: '' },
        { label: 'Animal Rearing', value: '' },
        { label: 'Anti-Magic', value: '' },
        { label: 'Anti-social Protagonist', value: '' },
        { label: 'Antihero Protagonist', value: '' },
        { label: 'Antique Shop', value: '' },
        { label: 'Apartment Life', value: '' },
        { label: 'Apathetic Protagonist', value: '' },
        { label: 'Apocalypse', value: '' },
        { label: 'Appearance Changes', value: '' },
        { label: 'Appearance Different from Actual Age', value: '' },
        { label: 'Archery', value: '' },
        { label: 'Aristocracy', value: '' },
        { label: 'Arms Dealers', value: '' },
        { label: 'Army', value: '' },
        { label: 'Army Building', value: '' },
        { label: 'Arranged Marriage', value: '' },
        { label: 'Arrogant Characters', value: '' },
        { label: 'Artifact Crafting', value: '' },
        { label: 'Artifacts', value: '' },
        { label: 'Artificial Intelligence', value: '' },
        { label: 'Artists', value: '' },
        { label: 'Assassins', value: '' },
        { label: 'Astrologers', value: '' },
        { label: 'Autism', value: '' },
        { label: 'Automatons', value: '' },
        { label: 'Average-looking Protagonist', value: '' },
        { label: 'Awkward Protagonist', value: '' },
        { label: 'Bands', value: '' },
        { label: 'Based on a Movie', value: '' },
        { label: 'Based on a Song', value: '' },
        { label: 'Based on a Video Game', value: '' },
        { label: 'Based on a Visual Novel', value: '' },
        { label: 'Based on an Anime', value: '' },
        { label: 'Battle Academy', value: '' },
        { label: 'Battle Competition', value: '' },
        { label: 'BDSM', value: '' },
        { label: 'Beast Companions', value: '' },
        { label: 'Beastkin', value: '' },
        { label: 'Beasts', value: '' },
        { label: 'Beautiful Couple', value: '' },
        { label: 'Beautiful Female Lead', value: '' },
        { label: 'Betrayal', value: '' },
        { label: 'Bickering Couple', value: '' },
        { label: 'Biochip', value: '' },
        { label: 'Biography', value: '' },
        { label: 'Bisexual Protagonist', value: '' },
        { label: 'Black Belly', value: '' },
        { label: 'Blackmail', value: '' },
        { label: 'Blacksmith', value: '' },
        { label: 'Blind Dates', value: '' },
        { label: 'Blind Protagonist', value: '' },
        { label: 'Blood Manipulation', value: '' },
        { label: 'Bloodlines', value: '' },
        { label: 'Body Swap', value: '' },
        { label: 'Body Tempering', value: '' },
        { label: 'Body-double', value: '' },
        { label: 'Bodyguards', value: '' },
        { label: 'Books', value: '' },
        { label: 'Bookworm', value: '' },
        { label: 'Boss-Subordinate Relationship', value: '' },
        { label: 'Boy_s Love Subplot', value: '' },
        { label: 'Brainwashing', value: '' },
        { label: 'Broken Engagement', value: '' },
        { label: 'Brother Complex', value: '' },
        { label: 'Brotherhood', value: '' },
        { label: 'Buddhism', value: '' },
        { label: 'Bullying', value: '' },
        { label: 'Business Management', value: '' },
        { label: 'Businessmen', value: '' },
        { label: 'Butlers', value: '' },
        { label: 'Calm Protagonist', value: '' },
        { label: 'Cannibalism', value: '' },
        { label: 'Card Games', value: '' },
        { label: 'Carefree Protagonist', value: '' },
        { label: 'Caring Protagonist', value: '' },
        { label: 'Cautious Protagonist', value: '' },
        { label: 'Celebrities', value: '' },
        { label: 'Character Growth', value: '' },
        { label: 'Charismatic Protagonist', value: '' },
        { label: 'Charming Protagonist', value: '' },
        { label: 'Chat Rooms', value: '' },
        { label: 'Cheating', value: '' },
        { label: 'Cheats', value: '' },
        { label: 'Chefs', value: '' },
        { label: 'Child Abuse', value: '' },
        { label: 'Child Protagonist', value: '' },
        { label: 'Childcare', value: '' },
        { label: 'Childhood Friends', value: '' },
        { label: 'Childhood Love', value: '' },
        { label: 'Childhood Promise', value: '' },
        { label: 'Childish Protagonist', value: '' },
        { label: 'Chuunibyou', value: '' },
        { label: 'Clan Building', value: '' },
        { label: 'Classic', value: '' },
        { label: 'Clever Protagonist', value: '' },
        { label: 'Clingy Lover', value: '' },
        { label: 'Clones', value: '' },
        { label: 'Clubs', value: '' },
        { label: 'Clumsy Love Interests', value: '' },
        { label: 'Co-Workers', value: '' },
        { label: 'Cohabitation', value: '' },
        { label: 'Cold Love Interests', value: '' },
        { label: 'Cold Protagonist', value: '' },
        { label: 'Collection of Short Stories', value: '' },
        { label: 'College/University', value: '' },
        { label: 'Coma', value: '' },
        { label: 'Comedic Undertone', value: '' },
        { label: 'Coming of Age', value: '' },
        { label: 'Complex Family Relationships', value: '' },
        { label: 'Conditional Power', value: '' },
        { label: 'Confident Protagonist', value: '' },
        { label: 'Confinement', value: '' },
        { label: 'Conflicting Loyalties', value: '' },
        { label: 'Conspiracies', value: '' },
        { label: 'Contracts', value: '' },
        { label: 'Cooking', value: '' },
        { label: 'Corruption', value: '' },
        { label: 'Cosmic Wars', value: '' },
        { label: 'Cosplay', value: '' },
        { label: 'Couple Growth', value: '' },
        { label: 'Court Official', value: '' },
        { label: 'Cousins', value: '' },
        { label: 'Cowardly Protagonist', value: '' },
        { label: 'Crafting', value: '' },
        { label: 'Crazy Protagonist', value: '' },
        { label: 'Crime', value: '' },
        { label: 'Criminals', value: '' },
        { label: 'Cross-dressing', value: '' },
        { label: 'Crossover', value: '' },
        { label: 'Cruel Characters', value: '' },
        { label: 'Cryostasis', value: '' },
        { label: 'Cultivation', value: '' },
        { label: 'Cunning Protagonist', value: '' },
        { label: 'Curious Protagonist', value: '' },
        { label: 'Curses', value: '' },
        { label: 'Cute Children', value: '' },
        { label: 'Cute Protagonist', value: '' },
        { label: 'Cute Story', value: '' },
        { label: 'Cyberpunk', value: '' },
        { label: 'Dancers', value: '' },
        { label: 'Dao Companion', value: '' },
        { label: 'Dao Comprehension', value: '' },
        { label: 'Daoism', value: '' },
        { label: 'Dark', value: '' },
        { label: 'Dead Protagonist', value: '' },
        { label: 'Death', value: '' },
        { label: 'Death of Loved Ones', value: '' },
        { label: 'Debts', value: '' },
        { label: 'Delinquents', value: '' },
        { label: 'Delusions', value: '' },
        { label: 'Demi-Humans', value: '' },
        { label: 'Demon Lord', value: '' },
        { label: 'Demonic Cultivation Technique', value: '' },
        { label: 'Demons', value: '' },
        { label: 'Dense Protagonist', value: '' },
        { label: 'Depictions of Cruelty', value: '' },
        { label: 'Depression', value: '' },
        { label: 'Destiny', value: '' },
        { label: 'Detectives', value: '' },
        { label: 'Determined Protagonist', value: '' },
        { label: 'Devoted Love Interests', value: '' },
        { label: 'Different Social Status', value: '' },
        { label: 'Disabilities', value: '' },
        { label: 'Discrimination', value: '' },
        { label: 'Disfigurement', value: '' },
        { label: 'Dishonest Protagonist', value: '' },
        { label: 'Distrustful Protagonist', value: '' },
        { label: 'Divination', value: '' },
        { label: 'Divine Protection', value: '' },
        { label: 'Divorce', value: '' },
        { label: 'Doctors', value: '' },
        { label: 'Dolls/Puppets', value: '' },
        { label: 'Domestic Affairs', value: '' },
        { label: 'Doting Love Interests', value: '' },
        { label: 'Doting Older Siblings', value: '' },
        { label: 'Doting Parents', value: '' },
        { label: 'Dragon Riders', value: '' },
        { label: 'Dragon Slayers', value: '' },
        { label: 'Dragons', value: '' },
        { label: 'Dreams', value: '' },
        { label: 'Drugs', value: '' },
        { label: 'Druids', value: '' },
        { label: 'Dungeon Master', value: '' },
        { label: 'Dungeons', value: '' },
        { label: 'Dwarfs', value: '' },
        { label: 'Dystopia', value: '' },
        { label: 'e-Sports', value: '' },
        { label: 'Early Romance', value: '' },
        { label: 'Earth Invasion', value: '' },
        { label: 'Easy Going Life', value: '' },
        { label: 'Economics', value: '' },
        { label: 'Editors', value: '' },
        { label: 'Eidetic Memory', value: '' },
        { label: 'Elderly Protagonist', value: '' },
        { label: 'Elemental Magic', value: '' },
        { label: 'Elves', value: '' },
        { label: 'Emotionally Weak Protagonist', value: '' },
        { label: 'Empires', value: '' },
        { label: 'Enemies Become Allies', value: '' },
        { label: 'Enemies Become Lovers', value: '' },
        { label: 'Engagement', value: '' },
        { label: 'Engineer', value: '' },
        { label: 'Enlightenment', value: '' },
        { label: 'Episodic', value: '' },
        { label: 'Eunuch', value: '' },
        { label: 'European Ambience', value: '' },
        { label: 'Evil Gods', value: '' },
        { label: 'Evil Organizations', value: '' },
        { label: 'Evil Protagonist', value: '' },
        { label: 'Evil Religions', value: '' },
        { label: 'Evolution', value: '' },
        { label: 'Exhibitionism', value: '' },
        { label: 'Exorcism', value: '' },
        { label: 'Eye Powers', value: '' },
        { label: 'Fairies', value: '' },
        { label: 'Fallen Angels', value: '' },
        { label: 'Fallen Nobility', value: '' },
        { label: 'Familial Love', value: '' },
        { label: 'Familiars', value: '' },
        { label: 'Family', value: '' },
        { label: 'Family Business', value: '' },
        { label: 'Family Conflict', value: '' },
        { label: 'Famous Parents', value: '' },
        { label: 'Famous Protagonist', value: '' },
        { label: 'Fanaticism', value: '' },
        { label: 'Fantasy Creatures', value: '' },
        { label: 'Fantasy World', value: '' },
        { label: 'Farming', value: '' },
        { label: 'Fast Cultivation', value: '' },
        { label: 'Fast Learner', value: '' },
        { label: 'Fat Protagonist', value: '' },
        { label: 'Fat to Fit', value: '' },
        { label: 'Fated Lovers', value: '' },
        { label: 'Fearless Protagonist', value: '' },
        { label: 'Female Master', value: '' },
        { label: 'Female Protagonist', value: '' },
        { label: 'Female to Male', value: '' },
        { label: 'Feng Shui', value: '' },
        { label: 'Firearms', value: '' },
        { label: 'First Love', value: '' },
        { label: 'First-time Intercourse', value: '' },
        { label: 'Flashbacks', value: '' },
        { label: 'Fleet Battles', value: '' },
        { label: 'Folklore', value: '' },
        { label: 'Forced into a Relationship', value: '' },
        { label: 'Forced Living Arrangements', value: '' },
        { label: 'Forced Marriage', value: '' },
        { label: 'Forgetful Protagonist', value: '' },
        { label: 'Former Hero', value: '' },
        { label: 'Fourth Wall', value: '' },
        { label: 'Fox Spirits', value: '' },
        { label: 'Friends Become Enemies', value: '' },
        { label: 'Friendship', value: '' },
        { label: 'Fujoshi', value: '' },
        { label: 'Futanari', value: '' },
        { label: 'Futuristic Setting', value: '' },
        { label: 'Galge', value: '' },
        { label: 'Gambling', value: '' },
        { label: 'Game Elements', value: '' },
        { label: 'Game Ranking System', value: '' },
        { label: 'Gamers', value: '' },
        { label: 'Gangs', value: '' },
        { label: 'Gate to Another World', value: '' },
        { label: 'Genderless Protagonist', value: '' },
        { label: 'Generals', value: '' },
        { label: 'Genetic Modifications', value: '' },
        { label: 'Genies', value: '' },
        { label: 'Genius Protagonist', value: '' },
        { label: 'Ghosts', value: '' },
        { label: 'Girl_s Love Subplot', value: '' },
        { label: 'Gladiators', value: '' },
        { label: 'Glasses-wearing Love Interests', value: '' },
        { label: 'Glasses-wearing Protagonist', value: '' },
        { label: 'Goblins', value: '' },
        { label: 'God Protagonist', value: '' },
        { label: 'God-human Relationship', value: '' },
        { label: 'Goddesses', value: '' },
        { label: 'Godly Powers', value: '' },
        { label: 'Gods', value: '' },
        { label: 'Golems', value: '' },
        { label: 'Gore', value: '' },
        { label: 'Grave Keepers', value: '' },
        { label: 'Grinding', value: '' },
        { label: 'Guardian Relationship', value: '' },
        { label: 'Guilds', value: '' },
        { label: 'Gunfighters', value: '' },
        { label: 'Hackers', value: '' },
        { label: 'Half-human Protagonist', value: '' },
        { label: 'Handjob', value: '' },
        { label: 'Handsome Male Lead', value: '' },
        { label: 'Hard-Working Protagonist', value: '' },
        { label: 'Harem-seeking Protagonist', value: '' },
        { label: 'Harsh Training', value: '' },
        { label: 'Hated Protagonist', value: '' },
        { label: 'Healers', value: '' },
        { label: 'Healing', value: '' },
        { label: 'Heartwarming', value: '' },
        { label: 'Heaven', value: '' },
        { label: 'Heavenly Tribulation', value: '' },
        { label: 'Hell', value: '' },
        { label: 'Helpful Protagonist', value: '' },
        { label: 'Herbalist', value: '' },
        { label: 'Heroes', value: '' },
        { label: 'Heterochromia', value: '' },
        { label: 'Hidden Abilities', value: '' },
        { label: 'Hiding True Abilities', value: '' },
        { label: 'Hiding True Identity', value: '' },
        { label: 'Hikikomori', value: '' },
        { label: 'Homunculus', value: '' },
        { label: 'Honest Protagonist', value: '' },
        { label: 'Hospital', value: '' },
        { label: 'Hot-blooded Protagonist', value: '' },
        { label: 'Human Experimentation', value: '' },
        { label: 'Human Weapon', value: '' },
        { label: 'Human-Nonhuman Relationship', value: '' },
        { label: 'Humanoid Protagonist', value: '' },
        { label: 'Hunters', value: '' },
        { label: 'Hypnotism', value: '' },
        { label: 'Identity Crisis', value: '' },
        { label: 'Imaginary Friend', value: '' },
        { label: 'Immortals', value: '' },
        { label: 'Imperial Harem', value: '' },
        { label: 'Incest', value: '' },
        { label: 'Incubus', value: '' },
        { label: 'Indecisive Protagonist', value: '' },
        { label: 'Industrialization', value: '' },
        { label: 'Inferiority Complex', value: '' },
        { label: 'Inheritance', value: '' },
        { label: 'Inscriptions', value: '' },
        { label: 'Insects', value: '' },
        { label: 'Interconnected Storylines', value: '' },
        { label: 'Interdimensional Travel', value: '' },
        { label: 'Introverted Protagonist', value: '' },
        { label: 'Investigations', value: '' },
        { label: 'Invisibility', value: '' },
        { label: 'Jack of All Trades', value: '' },
        { label: 'Jealousy', value: '' },
        { label: 'Jiangshi', value: '' },
        { label: 'Jobless Class', value: '' },
        { label: 'Kidnappings', value: '' },
        { label: 'Kind Love Interests', value: '' },
        { label: 'Kingdom Building', value: '' },
        { label: 'Kingdoms', value: '' },
        { label: 'Knights', value: '' },
        { label: 'Kuudere', value: '' },
        { label: 'Lack of Common Sense', value: '' },
        { label: 'Language Barrier', value: '' },
        { label: 'Late Romance', value: '' },
        { label: 'Lawyers', value: '' },
        { label: 'Lazy Protagonist', value: '' },
        { label: 'Leadership', value: '' },
        { label: 'Legends', value: '' },
        { label: 'Level System', value: '' },
        { label: 'Library', value: '' },
        { label: 'Limited Lifespan', value: '' },
        { label: 'Living Abroad', value: '' },
        { label: 'Living Alone', value: '' },
        { label: 'Loli', value: '' },
        { label: 'Loneliness', value: '' },
        { label: 'Loner Protagonist', value: '' },
        { label: 'Long Separations', value: '' },
        { label: 'Long-distance Relationship', value: '' },
        { label: 'Lost Civilizations', value: '' },
        { label: 'Lottery', value: '' },
        { label: 'Love at First Sight', value: '' },
        { label: 'Love Interest Falls in Love First', value: '' },
        { label: 'Love Rivals', value: '' },
        { label: 'Love Triangles', value: '' },
        { label: 'Lovers Reunited', value: '' },
        { label: 'Low-key Protagonist', value: '' },
        { label: 'Loyal Subordinates', value: '' },
        { label: 'Lucky Protagonist', value: '' },
        { label: 'Magic', value: '' },
        { label: 'Magic Beasts', value: '' },
        { label: 'Magic Formations', value: '' },
        { label: 'Magical Girls', value: '' },
        { label: 'Magical Space', value: '' },
        { label: 'Magical Technology', value: '' },
        { label: 'Maids', value: '' },
        { label: 'Male Protagonist', value: '' },
        { label: 'Male to Female', value: '' },
        { label: 'Male Yandere', value: '' },
        { label: 'Management', value: '' },
        { label: 'Mangaka', value: '' },
        { label: 'Manipulative Characters', value: '' },
        { label: 'Manly Gay Couple', value: '' },
        { label: 'Marriage', value: '' },
        { label: 'Marriage of Convenience', value: '' },
        { label: 'Martial Spirits', value: '' },
        { label: 'Masochistic Characters', value: '' },
        { label: 'Master-Disciple Relationship', value: '' },
        { label: 'Master-Servant Relationship', value: '' },
        { label: 'Masturbation', value: '' },
        { label: 'Matriarchy', value: '' },
        { label: 'Mature Protagonist', value: '' },
        { label: 'Medical Knowledge', value: '' },
        { label: 'Medieval', value: '' },
        { label: 'Mercenaries', value: '' },
        { label: 'Merchants', value: '' },
        { label: 'Military', value: '' },
        { label: 'Mind Break', value: '' },
        { label: 'Mind Control', value: '' },
        { label: 'Misandry', value: '' },
        { label: 'Mismatched Couple', value: '' },
        { label: 'Misunderstandings', value: '' },
        { label: 'MMORPG', value: '' },
        { label: 'Mob Protagonist', value: '' },
        { label: 'Models', value: '' },
        { label: 'Modern Day', value: '' },
        { label: 'Modern Fantasy', value: '' },
        { label: 'Modern Knowledge', value: '' },
        { label: 'Modern Time', value: '' },
        { label: 'Money Grubber', value: '' },
        { label: 'Monster Girls', value: '' },
        { label: 'Monster Society', value: '' },
        { label: 'Monster Tamer', value: '' },
        { label: 'Monsters', value: '' },
        { label: 'Movies', value: '' },
        { label: 'Mpreg', value: '' },
        { label: 'Multiple Identities', value: '' },
        { label: 'Multiple Personalities', value: '' },
        { label: 'Multiple POV', value: '' },
        { label: 'Multiple Protagonists', value: '' },
        { label: 'Multiple Realms', value: '' },
        { label: 'Multiple Reincarnated Individuals', value: '' },
        { label: 'Multiple Timelines', value: '' },
        { label: 'Multiple Transported Individuals', value: '' },
        { label: 'Murders', value: '' },
        { label: 'Music', value: '' },
        { label: 'Mutated Creatures', value: '' },
        { label: 'Mutations', value: '' },
        { label: 'Mute Character', value: '' },
        { label: 'Mysterious Family Background', value: '' },
        { label: 'Mysterious Illness', value: '' },
        { label: 'Mysterious Past', value: '' },
        { label: 'Mystery Solving', value: '' },
        { label: 'Mythical Beasts', value: '' },
        { label: 'Mythology', value: '' },
        { label: 'Naive Protagonist', value: '' },
        { label: 'Narcissistic Protagonist', value: '' },
        { label: 'Nationalism', value: '' },
        { label: 'Near-Death Experience', value: '' },
        { label: 'Necromancer', value: '' },
        { label: 'Neet', value: '' },
        { label: 'Netorare', value: '' },
        { label: 'Netorase', value: '' },
        { label: 'Netori', value: '' },
        { label: 'Nightmares', value: '' },
        { label: 'Ninjas', value: '' },
        { label: 'Nobles', value: '' },
        { label: 'Non-human Protagonist', value: '' },
        { label: 'Non-humanoid Protagonist', value: '' },
        { label: 'Non-linear Storytelling', value: '' },
        { label: 'Nudity', value: '' },
        { label: 'Nurses', value: '' },
        { label: 'Obsessive Love', value: '' },
        { label: 'Office Romance', value: '' },
        { label: 'Older Love Interests', value: '' },
        { label: 'Omegaverse', value: '' },
        { label: 'Oneshot', value: '' },
        { label: 'Online Romance', value: '' },
        { label: 'Onmyouji', value: '' },
        { label: 'Orcs', value: '' },
        { label: 'Organized Crime', value: '' },
        { label: 'Orphans', value: '' },
        { label: 'Otaku', value: '' },
        { label: 'Otome Game', value: '' },
        { label: 'Outcasts', value: '' },
        { label: 'Outdoor Intercourse', value: '' },
        { label: 'Outer Space', value: '' },
        { label: 'Overpowered Protagonist', value: '' },
        { label: 'Overprotective Siblings', value: '' },
        { label: 'Pacifist Protagonist', value: '' },
        { label: 'Paizuri', value: '' },
        { label: 'Pansexual Protagonist', value: '' },
        { label: 'Parallel Worlds', value: '' },
        { label: 'Parasites', value: '' },
        { label: 'Parent Complex', value: '' },
        { label: 'Parody', value: '' },
        { label: 'Part-Time Job', value: '' },
        { label: 'Past Plays a Big Role', value: '' },
        { label: 'Past Trauma', value: '' },
        { label: 'Persistent Love Interests', value: '' },
        { label: 'Personality Changes', value: '' },
        { label: 'Perverted Protagonist', value: '' },
        { label: 'Pets', value: '' },
        { label: 'Pharmacist', value: '' },
        { label: 'Philosophical', value: '' },
        { label: 'Phobias', value: '' },
        { label: 'Phoenixes', value: '' },
        { label: 'Photography', value: '' },
        { label: 'Pill Based Cultivation', value: '' },
        { label: 'Pill Concocting', value: '' },
        { label: 'Pilots', value: '' },
        { label: 'Pirates', value: '' },
        { label: 'Playboys', value: '' },
        { label: 'Playful Protagonist', value: '' },
        { label: 'Poetry', value: '' },
        { label: 'Poisons', value: '' },
        { label: 'Police', value: '' },
        { label: 'Polite Protagonist', value: '' },
        { label: 'Politics', value: '' },
        { label: 'Polyandry', value: '' },
        { label: 'Polygamy', value: '' },
        { label: 'Poor Protagonist', value: '' },
        { label: 'Poor to Rich', value: '' },
        { label: 'Popular Love Interests', value: '' },
        { label: 'Possession', value: '' },
        { label: 'Possessive Characters', value: '' },
        { label: 'Post-apocalyptic', value: '' },
        { label: 'Power Couple', value: '' },
        { label: 'Power Struggle', value: '' },
        { label: 'Pragmatic Protagonist', value: '' },
        { label: 'Precognition', value: '' },
        { label: 'Pregnancy', value: '' },
        { label: 'Pretend Lovers', value: '' },
        { label: 'Previous Life Talent', value: '' },
        { label: 'Priestesses', value: '' },
        { label: 'Priests', value: '' },
        { label: 'Prison', value: '' },
        { label: 'Proactive Protagonist', value: '' },
        { label: 'Programmer', value: '' },
        { label: 'Prophecies', value: '' },
        { label: 'Prostitutes', value: '' },
        { label: 'Protagonist Falls in Love First', value: '' },
        { label: 'Protagonist Loyal to Love Interest', value: '' },
        { label: 'Protagonist Strong from the Start', value: '' },
        { label: 'Protagonist with Multiple Bodies', value: '' },
        { label: 'Psychic Powers', value: '' },
        { label: 'Psychopaths', value: '' },
        { label: 'Puppeteers', value: '' },
        { label: 'Quiet Characters', value: '' },
        { label: 'Quirky Characters', value: '' },
        { label: 'R-15', value: '' },
        { label: 'R-18', value: '' },
        { label: 'Race Change', value: '' },
        { label: 'Racism', value: '' },
        { label: 'Rape', value: '' },
        { label: 'Rebellion', value: '' },
        { label: 'Reincarnated as a Monster', value: '' },
        { label: 'Reincarnated as an Object', value: '' },
        { label: 'Reincarnated into a Game World', value: '' },
        { label: 'Reincarnated into Another World', value: '' },
        { label: 'Reincarnation', value: '' },
        { label: 'Religions', value: '' },
        { label: 'Reluctant Protagonist', value: '' },
        { label: 'Reporters', value: '' },
        { label: 'Restaurant', value: '' },
        { label: 'Resurrection', value: '' },
        { label: 'Returning from Another World', value: '' },
        { label: 'Revenge', value: '' },
        { label: 'Reverse Harem', value: '' },
        { label: 'Reverse Rape', value: '' },
        { label: 'Rich to Poor', value: '' },
        { label: 'Righteous Protagonist', value: '' },
        { label: 'Rivalry', value: '' },
        { label: 'Romantic Subplot', value: '' },
        { label: 'Roommates', value: '' },
        { label: 'Royalty', value: '' },
        { label: 'RPG', value: '' },
        { label: 'Ruthless Protagonist', value: '' },
        { label: 'Sadistic Characters', value: '' },
        { label: 'Saints', value: '' },
        { label: 'Salaryman', value: '' },
        { label: 'Samurai', value: '' },
        { label: 'Satire', value: '' },
        { label: 'Saving the World', value: '' },
        { label: 'Scheming', value: '' },
        { label: 'Schizophrenia', value: '' },
        { label: 'Scientists', value: '' },
        { label: 'Sculptors', value: '' },
        { label: 'Sealed Power', value: '' },
        { label: 'Second Chance', value: '' },
        { label: 'Secret Crush', value: '' },
        { label: 'Secret Identity', value: '' },
        { label: 'Secret Organizations', value: '' },
        { label: 'Secret Relationship', value: '' },
        { label: 'Secretive Protagonist', value: '' },
        { label: 'Secrets', value: '' },
        { label: 'Sect Development', value: '' },
        { label: 'Seduction', value: '' },
        { label: 'Seeing Things Other Humans Can_t', value: '' },
        { label: 'Selfish Protagonist', value: '' },
        { label: 'Selfless Protagonist', value: '' },
        { label: 'Seme Protagonist', value: '' },
        { label: 'Senpai-Kouhai Relationship', value: '' },
        { label: 'Sentient Objects', value: '' },
        { label: 'Sentimental Protagonist', value: '' },
        { label: 'Serial Killers', value: '' },
        { label: 'Servants', value: '' },
        { label: 'Seven Deadly Sins', value: '' },
        { label: 'Seven Virtues', value: '' },
        { label: 'Sex Friends', value: '' },
        { label: 'Sexual Abuse', value: '' },
        { label: 'Sexual Cultivation Technique', value: '' },
        { label: 'Shameless Protagonist', value: '' },
        { label: 'Shapeshifters', value: '' },
        { label: 'Sharing A Body', value: '' },
        { label: 'Sharp-tongued Characters', value: '' },
        { label: 'Shield User', value: '' },
        { label: 'Shikigami', value: '' },
        { label: 'Short Story', value: '' },
        { label: 'Shota', value: '' },
        { label: 'Showbiz', value: '' },
        { label: 'Shy Characters', value: '' },
        { label: 'Sibling Rivalry', value: '' },
        { label: 'Siblings', value: '' },
        { label: 'Siblings Care', value: '' },
        { label: 'Siblings Not Related by Blood', value: '' },
        { label: 'Sickly Characters', value: '' },
        { label: 'Sign Language', value: '' },
        { label: 'Singers', value: '' },
        { label: 'Single Parent', value: '' },
        { label: 'Sister Complex', value: '' },
        { label: 'Skill Assimilation', value: '' },
        { label: 'Skill Books', value: '' },
        { label: 'Skill Creation', value: '' },
        { label: 'Slave Harem', value: '' },
        { label: 'Slave Protagonist', value: '' },
        { label: 'Slaves', value: '' },
        { label: 'Sleeping', value: '' },
        { label: 'Slow Growth at Start', value: '' },
        { label: 'Slow Romance', value: '' },
        { label: 'Smart Couple', value: '' },
        { label: 'Social Outcasts', value: '' },
        { label: 'Soldiers', value: '' },
        { label: 'Soul Power', value: '' },
        { label: 'Souls', value: '' },
        { label: 'Spatial Manipulation', value: '' },
        { label: 'Spear Wielder', value: '' },
        { label: 'Special Abilities', value: '' },
        { label: 'Special Forces', value: '' },
        { label: 'Spies', value: '' },
        { label: 'Spirit Advisor', value: '' },
        { label: 'Spirit Users', value: '' },
        { label: 'Spirits', value: '' },
        { label: 'Stalkers', value: '' },
        { label: 'Stockholm Syndrome', value: '' },
        { label: 'Stoic Characters', value: '' },
        { label: 'Store Owner', value: '' },
        { label: 'Straight Seme', value: '' },
        { label: 'Straight Uke', value: '' },
        { label: 'Strategic Battles', value: '' },
        { label: 'Strategist', value: '' },
        { label: 'Strength-based Social Hierarchy', value: '' },
        { label: 'Strong Love Interests', value: '' },
        { label: 'Strong to Stronger', value: '' },
        { label: 'Stubborn Protagonist', value: '' },
        { label: 'Student Council', value: '' },
        { label: 'Student-Teacher Relationship', value: '' },
        { label: 'Subtle Romance', value: '' },
        { label: 'Succubus', value: '' },
        { label: 'Sudden Strength Gain', value: '' },
        { label: 'Sudden Wealth', value: '' },
        { label: 'Suicides', value: '' },
        { label: 'Summoned Hero', value: '' },
        { label: 'Summoning Magic', value: '' },
        { label: 'Superheroes', value: '' },
        { label: 'Survival', value: '' },
        { label: 'Survival Game', value: '' },
        { label: 'Sword And Magic', value: '' },
        { label: 'Sword Wielder', value: '' },
        { label: 'System Administrator', value: '' },
        { label: 'Teachers', value: '' },
        { label: 'Teamwork', value: '' },
        { label: 'Technological Gap', value: '' },
        { label: 'Tentacles', value: '' },
        { label: 'Terminal Illness', value: '' },
        { label: 'Terrorists', value: '' },
        { label: 'Thieves', value: '' },
        { label: 'Threesome', value: '' },
        { label: 'Thriller', value: '' },
        { label: 'Time Loop', value: '' },
        { label: 'Time Manipulation', value: '' },
        { label: 'Time Paradox', value: '' },
        { label: 'Time Skip', value: '' },
        { label: 'Time Travel', value: '' },
        { label: 'Timid Protagonist', value: '' },
        { label: 'Tomboyish Female Lead', value: '' },
        { label: 'Torture', value: '' },
        { label: 'Toys', value: '' },
        { label: 'Tragic Past', value: '' },
        { label: 'Transformation Ability', value: '' },
        { label: 'Transgender', value: '' },
        { label: 'Transmigration', value: '' },
        { label: 'Transplanted Memories', value: '' },
        { label: 'Transported into a Game World', value: '' },
        { label: 'Transported into Another World', value: '' },
        { label: 'Transported Modern Structure', value: '' },
        { label: 'Trap', value: '' },
        { label: 'Tribal Society', value: '' },
        { label: 'Trickster', value: '' },
        { label: 'Trolls', value: '' },
        { label: 'Tsundere', value: '' },
        { label: 'Twins', value: '' },
        { label: 'Twisted Personality', value: '' },
        { label: 'Ugly Protagonist', value: '' },
        { label: 'Ugly to Beautiful', value: '' },
        { label: 'Unconditional Love', value: '' },
        { label: 'Underestimated Protagonist', value: '' },
        { label: 'Unique Cultivation Technique', value: '' },
        { label: 'Unique Weapon User', value: '' },
        { label: 'Unique Weapons', value: '' },
        { label: 'Unlucky Protagonist', value: '' },
        { label: 'Unreliable Narrator', value: '' },
        { label: 'Unrequited Love', value: '' },
        { label: 'Valkyries', value: '' },
        { label: 'Vampires', value: '' },
        { label: 'Villainess Noble Girls', value: '' },
        { label: 'Virtual Reality', value: '' },
        { label: 'Vocaloid', value: '' },
        { label: 'Voice Actors', value: '' },
        { label: 'Voyeurism', value: '' },
        { label: 'Waiters', value: '' },
        { label: 'War Records', value: '' },
        { label: 'Wars', value: '' },
        { label: 'Weak Protagonist', value: '' },
        { label: 'Weak to Strong', value: '' },
        { label: 'Wealthy Characters', value: '' },
        { label: 'Werebeasts', value: '' },
        { label: 'Wishes', value: '' },
        { label: 'Witches', value: '' },
        { label: 'Wizards', value: '' },
        { label: 'World Hopping', value: '' },
        { label: 'World Invasion', value: '' },
        { label: 'World Travel', value: '' },
        { label: 'World Tree', value: '' },
        { label: 'Writers', value: '' },
        { label: 'Wuxia', value: '' },
        { label: 'Xianxia', value: '' },
        { label: 'Xuanhuan', value: '' },
        { label: 'Yandere', value: '' },
        { label: 'Youkai', value: '' },
        { label: 'Younger Brothers', value: '' },
        { label: 'Younger Love Interests', value: '' },
        { label: 'Younger Sisters', value: '' },
        { label: 'Zombies', value: '' },
      ],
      type: FilterTypes.ExcludableCheckboxGroup,
    },
    content_warning_operator: {
      value: 'and',
      label: 'Mature Content (And/Or)',
      options: [
        { label: 'And', value: 'and' },
        { label: 'Or', value: 'or' },
      ],
      type: FilterTypes.Picker,
    },
    content_warning: {
      value: {
        include: [],
        exclude: [],
      },
      label: 'Mature Content',
      options: [
        { label: 'Gore', value: '48' },
        { label: 'Sexual Content', value: '50' },
        { label: 'Strong Language', value: '49' },
      ],
      type: FilterTypes.ExcludableCheckboxGroup,
    },
  } satisfies Filters;
}

export default new ScribbleHubPlugin();
